services:
  db:
    image: postgres:16
    container_name: rnaseq_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build: . 
    container_name: rnaseq_pipeline
    tty: true  # This keeps the container "awake" even after the script finishes
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    environment: 
      # Pass environment variables that match your db_config.yaml
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - .:/app  # Mount your source code if needed
    working_dir: /app
    command: python -m rnaseq.pipeline --config /app/config.yml

volumes:
  pgdata: 